/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        gray: {
          "100": "#fdfdfd",
          "200": "#8e8e8e",
          "300": "#202020",
          "400": "#1f1f1f",
          "500": "#1d1d1d",
          "600": "#181818",
          "700": "#fafafb",
        },
        "primary-p100": "#5c27c0",
        snow: "#fffbfb",
        white: "#f7f7f7",
        black: "#1c1c1c",
        darkslategray: "#3b3b3b",
        "primary-300": "#eee5ff",
        "neutrals-white": "#fafafa",
        "neutrals-300": "#6a6a6a",
        black1: "#000",
        white1: "#fff",
        dimgray: "#5b5b5b",
        goldenrod: "#ffb649",
        "primary-200": "#ad93df",
        whitesmoke: {
          "100": "#f7f7f8",
          "200": "#f6f6f6",
        },
        primary: "#605bff",
        text: "#030229",
        red: "#d11a2a",
        dodgerblue: "#5b93ff",
        cornflowerblue: "#80abff",
        pink: "#ffc7d4",
        badge: "#26c0e2",
        badge1: "#ef37ff",
        thistle: "#d5d3ff",
        darkgray: {
          "100": "#b3b3bf",
          "200": "#a4a4a4",
        },
        khaki: "#ffd66b",
        lightcoral: "#df6f79",
      },
      spacing: {},
      fontFamily: {
        "garnett-regular": "'Garnett Regular'",
        "garnett-semibold": "'Garnett Semibold'",
        poppins: "Poppins",
        "garnett-medium": "'Garnett Medium'",
        "space-grotesk": "'Space Grotesk'",
        "garnett-light": "'Garnett Light'",
        actor: "Actor",
        outfit: "Outfit",
        "gilroy-regular": "Gilroy-Regular",
        nunito: "Nunito",
        "google-sans": "'Google Sans'",
      },
      borderRadius: {
        xl: "20px",
        "3xs": "10px",
        "8xs": "5px",
        "7xs-7": "5.7px",
        "6xs": "7px",
        "3xl-5": "22.5px",
      },
    },
    fontSize: {
      "23xl": "42px",
      base: "16px",
      "5xl": "24px",
      lg: "18px",
      "19xl": "38px",
      "31xl": "50px",
      "4xl": "23px",
      "21xl": "40px",
      sm: "14px",
      "3xl": "22px",
      "smi-3": "12.3px",
      "5xl-9": "24.9px",
      "16xl-5": "35.5px",
      "xs-4": "11.4px",
      xs: "12px",
      "3xs": "10px",
      inherit: "inherit",
    },
    screens: {
      md: {
        max: "960px",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
